### ISSUE TITLE
使用idea创建项目后，log无法识别等错误

### ISSUE THREAD

**Issue by BruceOuyang** [drtrang/maven-archetype-springboot#1]
### 问题1：Application.java中的log无法识别
```java
log.info("this project is running...");
```
![image](https://user-images.githubusercontent.com/5382942/29397348-23525f78-8350-11e7-835c-dc805b5541f6.png)

### 问题2：util包里边，CsvUtils有2个异常
E1
![image](https://user-images.githubusercontent.com/5382942/29397401-7c53c15c-8350-11e7-984f-672760b54fe8.png)

E2
![image](https://user-images.githubusercontent.com/5382942/29397419-95e4222e-8350-11e7-879e-759f164936e5.png)

**Comment by drtrang** [comment]
这俩都是一个问题，你的运行环境缺少 [Lombok](https://projectlombok.org/features/all) 插件，IDEA 的话在 `Plugins` 中安装 `Lombok Plugin` 重启即可。

Lombok 插件能极大减轻工作量，推荐阅读文章：[Lombok:让JAVA代码更优雅](https://mp.weixin.qq.com/s?__biz=MzI0OTIzOTMzMA==&mid=2247483851&idx=1&sn=007ceceaa3a3e6fecbeb23873a230e19&chksm=e995c386dee24a90c9493949bd1cb159114f5d457d4354a93050c3a218c5d111a193406dff74&mpshare=1&scene=1&srcid=0606I1Vkahdws6aFa04Ytvpv#rd)

以下是 Intellij IDEA 中 `Lombok Plugin` 的截图：

![_20170817134759](https://user-images.githubusercontent.com/13851701/29397900-ddf447d0-8353-11e7-8be6-84886278366d.png)

**Comment by BruceOuyang** [comment]
感谢，可以跑起来了。
我在spring4all社区你发的文章下评论了一条，能不能把mokito（mock单元测试）也加进去，让它更加完美。

**Comment by drtrang** [comment]
`spring-boot-starter-test` 中有 junit、assertj、mockito、hamcrest 等工具的支持，只要引入了 `spring-boot-starter-test` 就会把这些 jar 包传递过来。

**Comment by BruceOuyang** [comment]
额~
